language: node_js
sudo: false
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
install:
  - npm install
before_script:
  - cp src/config.sample.js src/config.js
script:
  - npm test
notifications:
  email: false
